import turtle

window = turtle.Screen()
window.bgcolor("black") 

brad = turtle.Turtle()
brad.pensize(5)
brad.shape("arrow")
brad.color("white")
brad.fillcolor('red')

brad.begin_fill()
brad.left(0)
brad.forward(60)
brad.left(90)
brad.forward(75)
brad.left(270)
brad.forward(60)
brad.left(270)
brad.forward(75)
brad.left(90)
brad.forward(60)
brad.left(90)
brad.forward(90)
brad.left(270)
brad.forward(45)
brad.left(135)
brad.forward(190)
brad.left(90)
brad.forward(190)
brad.left(135)
brad.forward(45)
brad.left(270)
brad.forward(90)
brad.end_fill()

brad.hideturtle()

window.exitonclick()
